obj-y += mips_r4k.o mips_jazz.o mips_malta.o mips_mipssim.o
obj-y += addr.o cputimer.o mips_int.o
obj-$(CONFIG_FULONG) += mips_fulong2e.o
obj-$(CONFIG_JZ4780) += jz4780.o jz4780-cgu.o jz4780-tcu.o jz47xx-intc.o
obj-y += gt64xxx_pci.o
